apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.claimName }}
spec:
  accessModes: 
    - RReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvcRequestStorage }}